### ISSUE TITLE
How to use translation module

### ISSUE THREAD

**Issue by hasanOryx** [dart-lang/intl#195]
It is not clear for me how to use it, let's say I've the same example you mentioned:

```
  String continueMessage() => Intl.message(
      "Hit any key to continue",
      name: "continueMessage",
      args: [],
      desc: "Explains that we will not proceed further until "
          "the user presses a key");
  print(continueMessage());
```

I read this block as well, but dd not get it:

```
  dev_dependencies:
    intl_translation: ^0.15.0
  transformers:
  - intl_translation:
  $include: some_file.dart
```

I want to use the following locale: English, Spanish and Arabic.
So, what next, where and how shall I:
1. Write the Spanish and Arabic translation
2. Connect the translation to this module
