### ISSUE TITLE
Can multi-component development be supported ?

### ISSUE THREAD

**Issue by AlanGrey** [dart-lang/intl#384]
HI，I have a project need more module use intl , but When it`s assembled into a project , only one module is in effect;
I found the reason :
message_lookup_by_library.dart =>  lookupMessage() , this function just only save lastLookup ;

I try fork intl project to modify it ，but the project was quoted incorrectly ；
error : "Because project depends on flutter_localizations any from sdk which depends on int 0.16.0 , intl from hosted is required"
Can you help me out?

**Comment by kutear** [comment]
you can ref my repo : https://github.com/kutear/intl/commit/6d37bb1882e0c9bd38b77e05e96b9b0f63af33c2 

just like this.

```
dependencies:
  intl:
    git:
      url: https://github.com/kutear/intl.git
      ref: master

dependency_overrides:
  intl:
    git:
      url: https://github.com/kutear/intl.git
      ref: master
```
